import type { Conversation, Message } from "@/store/chat.store";

// ─── Mock Users ──────────────────────────────────────────────
export const CURRENT_USER = {
  user_id: "u-self",
  name: "Ashitosh Lavhate",
  avatar: undefined,
  presence_status: "ONLINE" as const,
};

export const MOCK_USERS = [
  { user_id: "u-1", name: "John Dsouza", avatar: undefined, presence_status: "ONLINE" as const },
  { user_id: "u-2", name: "Rahul Patil", avatar: undefined, presence_status: "ONLINE" as const },
  { user_id: "u-3", name: "Neha Joshi", avatar: undefined, presence_status: "AWAY" as const },
  { user_id: "u-4", name: "Vivek Deshmukh", avatar: undefined, presence_status: "OFFLINE" as const },
  { user_id: "u-5", name: "Ananya Rao", avatar: undefined, presence_status: "ONLINE" as const },
  { user_id: "u-6", name: "Pooja Sharma", avatar: undefined, presence_status: "OFFLINE" as const },
  { user_id: "u-7", name: "Prof. P. B. Kulkarni", avatar: undefined, presence_status: "ONLINE" as const, role: "FACULTY" },
  { user_id: "u-8", name: "Prof. A. B. Patil", avatar: undefined, presence_status: "AWAY" as const, role: "FACULTY" },
];

// ─── Mock Conversations ─────────────────────────────────────
export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    conv_id: "c-1",
    type: "GROUP",
    name: "DBMS Study Group",
    avatar: undefined,
    last_message: "Rahul: Can someone share the notes...",
    last_message_time: "10:30 AM",
    last_message_sender: "Rahul Patil",
    unread_count: 6,
    is_pinned: true,
    member_count: 24,
    description: "Discussion group for DBMS subject. Share notes, ask doubts and collaborate.",
    created_by: "u-7",
    members: [
      MOCK_USERS[6],
      MOCK_USERS[1],
      MOCK_USERS[0],
      MOCK_USERS[2],
      MOCK_USERS[3],
      MOCK_USERS[4],
    ],
  },
  {
    conv_id: "c-2",
    type: "GROUP",
    name: "Project Team Alpha",
    avatar: undefined,
    last_message: "You: Meeting at 4 PM today",
    last_message_time: "Yesterday",
    last_message_sender: "Ashitosh Lavhate",
    unread_count: 0,
    is_pinned: true,
    member_count: 5,
    description: "Final year project team for Smart Campus App.",
    created_by: "u-self",
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[4]],
  },
  {
    conv_id: "c-3",
    type: "DIRECT",
    name: "John Dsouza",
    avatar: undefined,
    last_message: "Thanks for the resources!",
    last_message_time: "09:15 AM",
    last_message_sender: "John Dsouza",
    unread_count: 2,
    is_pinned: false,
    members: [MOCK_USERS[0]],
  },
  {
    conv_id: "c-4",
    type: "SUBJECT_GROUP",
    name: "Computer Networks",
    avatar: undefined,
    last_message: "Prof. A. B. Patil: Lab schedule updated",
    last_message_time: "09:02 AM",
    last_message_sender: "Prof. A. B. Patil",
    unread_count: 3,
    is_pinned: false,
    member_count: 42,
    description: "Official Computer Networks subject group.",
    members: [MOCK_USERS[7], MOCK_USERS[0], MOCK_USERS[1]],
  },
  {
    conv_id: "c-5",
    type: "COMMUNITY",
    name: "AI & ML Community",
    avatar: undefined,
    last_message: "Neha: New resource uploaded!",
    last_message_time: "Yesterday",
    last_message_sender: "Neha Joshi",
    unread_count: 0,
    is_pinned: false,
    member_count: 1245,
    description: "Community for AI & ML enthusiasts at DES PU.",
    members: [MOCK_USERS[2], MOCK_USERS[4]],
  },
  {
    conv_id: "c-6",
    type: "COMMUNITY",
    name: "Open Source Club",
    avatar: undefined,
    last_message: "Vivek: Hackathon registrations open!",
    last_message_time: "Yesterday",
    last_message_sender: "Vivek Deshmukh",
    unread_count: 0,
    is_pinned: false,
    member_count: 893,
    description: "DES PU Open Source contribution community.",
    members: [MOCK_USERS[3], MOCK_USERS[0]],
  },
  {
    conv_id: "c-7",
    type: "DIRECT",
    name: "Pooja Sharma",
    avatar: undefined,
    last_message: "Okay, got it!",
    last_message_time: "Yesterday",
    last_message_sender: "Pooja Sharma",
    unread_count: 0,
    is_pinned: false,
    members: [MOCK_USERS[5]],
  },
  {
    conv_id: "c-8",
    type: "COMMUNITY",
    name: "Hackathon Hub",
    avatar: undefined,
    last_message: "Career Cell: New drive by Amazon...",
    last_message_time: "2 days ago",
    last_message_sender: "Career Cell",
    unread_count: 0,
    is_pinned: false,
    member_count: 567,
    description: "All hackathon updates and registrations.",
    members: [],
  },
];

// ─── Mock Messages for DBMS Study Group ─────────────────────
export const MOCK_MESSAGES_C1: Message[] = [
  {
    msg_id: "m-1",
    conv_id: "c-1",
    sender_id: "u-1",
    sender_name: "John Dsouza",
    content: "Hey Ashitosh! 👋",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T09:10:00+05:30",
  },
  {
    msg_id: "m-2",
    conv_id: "c-1",
    sender_id: "u-1",
    sender_name: "John Dsouza",
    content: "Can you share the DBMS assignment requirements?",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T09:10:30+05:30",
  },
  {
    msg_id: "m-3",
    conv_id: "c-1",
    sender_id: "u-self",
    sender_name: "Ashitosh Lavhate",
    content: "Hey John! Sure 👍",
    type: "TEXT",
    reactions: [{ emoji: "👍", count: 2, reacted: false }],
    is_deleted: false,
    is_own: true,
    read_by: ["u-1", "u-2"],
    status: "read",
    created_at: "2026-06-14T09:12:00+05:30",
  },
  {
    msg_id: "m-4",
    conv_id: "c-1",
    sender_id: "u-self",
    sender_name: "Ashitosh Lavhate",
    content: "Here you go",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: true,
    read_by: ["u-1", "u-2"],
    status: "read",
    created_at: "2026-06-14T09:12:10+05:30",
  },
  {
    msg_id: "m-5",
    conv_id: "c-1",
    sender_id: "u-self",
    sender_name: "Ashitosh Lavhate",
    content: "DBMS_Assignment.pdf",
    type: "FILE",
    attachment: {
      r2_key: "files/dbms-assignment.pdf",
      file_name: "DBMS_Assignment.pdf",
      file_size: 1258291,
      mime_type: "application/pdf",
    },
    reactions: [],
    is_deleted: false,
    is_own: true,
    read_by: ["u-1"],
    status: "read",
    created_at: "2026-06-14T09:12:20+05:30",
  },
  {
    msg_id: "m-6",
    conv_id: "c-1",
    sender_id: "u-1",
    sender_name: "John Dsouza",
    content: "Thanks! That helps a lot 😊",
    type: "TEXT",
    reactions: [{ emoji: "❤️", count: 1, reacted: true }],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T09:13:00+05:30",
  },
  {
    msg_id: "m-7",
    conv_id: "c-1",
    sender_id: "u-2",
    sender_name: "Rahul Patil",
    content: "",
    type: "POLL",
    poll: {
      poll_id: "p-1",
      question: "Where should we meet for the project discussion?",
      is_anonymous: false,
      is_multiple: false,
      expires_at: "2026-06-15T09:00:00+05:30",
      has_voted: true,
      total_votes: 16,
      options: [
        { option_id: "po-1", text: "Library", votes: 8, voted: true, percentage: 50 },
        { option_id: "po-2", text: "Lab 3", votes: 5, voted: false, percentage: 31 },
        { option_id: "po-3", text: "Cafeteria", votes: 3, voted: false, percentage: 19 },
      ],
    },
    reactions: [],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T09:13:30+05:30",
  },
  {
    msg_id: "m-8",
    conv_id: "c-1",
    sender_id: "u-self",
    sender_name: "Ashitosh Lavhate",
    content: "Library works best!",
    type: "TEXT",
    reactions: [{ emoji: "👍", count: 2, reacted: false }],
    is_deleted: false,
    is_own: true,
    read_by: ["u-1", "u-2"],
    status: "read",
    created_at: "2026-06-14T09:14:00+05:30",
  },
];

// ─── Mock Messages for Direct Chat with John ────────────────
export const MOCK_MESSAGES_C3: Message[] = [
  {
    msg_id: "dm-1",
    conv_id: "c-3",
    sender_id: "u-1",
    sender_name: "John Dsouza",
    content: "Hey! Did you check the new resources posted for CN?",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T08:45:00+05:30",
  },
  {
    msg_id: "dm-2",
    conv_id: "c-3",
    sender_id: "u-self",
    sender_name: "Ashitosh Lavhate",
    content: "Yeah I did! The network topology diagrams are really helpful.",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: true,
    read_by: ["u-1"],
    status: "read",
    created_at: "2026-06-14T08:50:00+05:30",
  },
  {
    msg_id: "dm-3",
    conv_id: "c-3",
    sender_id: "u-1",
    sender_name: "John Dsouza",
    content: "Thanks for the resources!",
    type: "TEXT",
    reactions: [],
    is_deleted: false,
    is_own: false,
    read_by: ["u-self"],
    status: "read",
    created_at: "2026-06-14T09:15:00+05:30",
  },
];

// ─── Message lookup ──────────────────────────────────────────
export const MOCK_MESSAGES: Record<string, Message[]> = {
  "c-1": MOCK_MESSAGES_C1,
  "c-3": MOCK_MESSAGES_C3,
};
