import type { FormSummary } from "@/store/form.store";

export const MOCK_FORMS: FormSummary[] = [
  {
    form_id: "f-1",
    title: "Semester Project Registration",
    description: "Register your final year project team and topic for the upcoming semester.",
    created_by: "u-7",
    creator_name: "Prof. P. B. Kulkarni",
    response_count: 45,
    is_active: true,
    is_draft: false,
    is_published: true,
    theme_color: "#E86E0A",
    created_at: "2026-06-10T10:00:00+05:30",
    updated_at: "2026-06-14T09:00:00+05:30",
  },
  {
    form_id: "f-2",
    title: "AI & ML Workshop Feedback",
    description: "Share your experience from the recent AI & ML workshop conducted by the department.",
    created_by: "u-self",
    creator_name: "Ashitosh Lavhate",
    response_count: 128,
    is_active: true,
    is_draft: false,
    is_published: true,
    theme_color: "#3B82F6",
    created_at: "2026-06-08T14:00:00+05:30",
    updated_at: "2026-06-13T11:00:00+05:30",
  },
  {
    form_id: "f-3",
    title: "Open Source Club Applications",
    description: "Apply to join the DES PU Open Source Club. We're looking for passionate developers!",
    created_by: "u-self",
    creator_name: "Ashitosh Lavhate",
    response_count: 32,
    is_active: true,
    is_draft: false,
    is_published: true,
    theme_color: "#10B981",
    created_at: "2026-06-05T09:00:00+05:30",
    updated_at: "2026-06-12T16:00:00+05:30",
  },
  {
    form_id: "f-4",
    title: "Hackathon Team Formation",
    description: "Find team members for the upcoming inter-university hackathon.",
    created_by: "u-3",
    creator_name: "Neha Joshi",
    response_count: 0,
    is_active: true,
    is_draft: true,
    is_published: false,
    theme_color: "#8B5CF6",
    created_at: "2026-06-13T20:00:00+05:30",
    updated_at: "2026-06-14T08:00:00+05:30",
  },
  {
    form_id: "f-5",
    title: "Placement Drive Preferences",
    description: "Tell us your company preferences and desired roles for the upcoming placement season.",
    created_by: "u-8",
    creator_name: "Prof. A. B. Patil",
    response_count: 156,
    is_active: true,
    is_draft: false,
    is_published: true,
    theme_color: "#F59E0B",
    created_at: "2026-06-01T08:00:00+05:30",
    updated_at: "2026-06-14T07:00:00+05:30",
  },
  {
    form_id: "f-6",
    title: "Club Event Volunteer Registration",
    description: "Sign up to volunteer for the Annual Tech Fest 2026.",
    created_by: "u-self",
    creator_name: "Ashitosh Lavhate",
    response_count: 0,
    is_active: true,
    is_draft: true,
    is_published: false,
    theme_color: "#EF4444",
    created_at: "2026-06-14T12:00:00+05:30",
    updated_at: "2026-06-14T12:00:00+05:30",
  },
];
